version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7

    working_directory: /dockerflow

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build docker image
          command: docker build -f Dockerfile -t fxa-activity-metrics .

      - run:
          name: Deploy to dockerhub
          shell: /bin/sh
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DOCKER_TAG="latest"
            fi

            if [[ "${CIRCLE_BRANCH}" == feature* ]] || [[ "${CIRCLE_BRANCH}" == dockerpush* ]]; then
              DOCKER_TAG="${CIRCLE_BRANCH}"
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            fi

            if [ -n "${DOCKER_TAG}" ]; then
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              echo ${DOCKERHUB_REPO}:${DOCKER_TAG}
              docker tag fxa-email-service:build ${DOCKERHUB_REPO}:${DOCKER_TAG}
              docker images
              docker push ${DOCKERHUB_REPO}:${DOCKER_TAG}
            fi

workflows:
  version: 2

  build-test-push:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/

            tags:
              only: /^v[0-9.]+$/
